add shebang to hook init

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if ! command -v dotnet &> /dev/null
+then
+    echo "dotnet command could not be found. Please install dotnet."
+    exit 1
+fi
+
 if ! command -v dotnet-csharpier &> /dev/null
 then
     echo "Installing dotnet-csharpier..."
